### PR TITLE
LRSD-6378 [CP 2.0] Fix deactivate keys table through actions button

### PR DESCRIPTION
**Pull request by pedroliveirav**
[LRSD-6378](https://liferay.atlassian.net/browse/LRSD-6378)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Comment by ryanschuhler** [comment]
ci:test:customer-solutions

**Comment by ryanschuhler** [comment]
ci:test:relevant

**Comment by amosfong** [comment]
Looks good to me. @ryanschuhler ?

**Review by ryanschuhler — APPROVED** [review]

**Comment by ryanschuhler** [comment]
ci:forward

**Pull request closed without merging**
