### PR TITLE
LRSD-7249 SaaS Metrics Dashboard (Add-Ons)

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by ryanschuhler** [comment]
ci:forward

**Comment by ryanschuhler** [comment]
thanks! https://github.com/brianchandotcom/liferay-portal/pull/156678

**Comment by amosfong** [comment]
what, why did this pass ci test sf and not the other PRs?

**Comment by ryanschuhler** [comment]
@amosfong I dont know, ci seems to be pretty flakey. when things fail its usually not even getting to the part where our code is even checked. hoping its back soon though

**Pull request closed without merging**
