### PR TITLE
LRSD-6920 [LRSD-6921] Fix API_BASE_URL

### PR DESCRIPTION
**Pull request by ryanschuhler**

### CODE REVIEW

**Comment by ryanschuhler** [comment]
@amosfong I am relatively certain this environment variable never gets set/used in uat or prod, and the way it is implemented causes issues running locally (and in ci I believe). Any thoughts or worries about this change?

**Comment by ryanschuhler** [comment]
ci:test

**Comment by amosfong** [comment]
ok, I'm not familiar with how this works

**Review by amosfong — APPROVED** [review]

**Comment by ryanschuhler** [comment]
ci:forward

**Pull request closed without merging**
