### PR TITLE
LRSD-5487 Enabling Account Restrictions for SaaS objects

### PR DESCRIPTION
**Pull request by jennyhchen**
https://liferay.atlassian.net/browse/LRSD-5487

### CODE REVIEW

**Comment by amosfong** [comment]
@jennyhchen , can you run `yarn format` from /modules? the trailing commas are actually intended

also, you wrote "Enabling Account Restrictions for SaaS objects", but I didnt see anything related to that. Is that possible through site initializer?

**Comment by jennyhchen** [comment]
> @jennyhchen , can you run `yarn format` from /modules? the trailing commas are actually intended
> 
> also, you wrote "Enabling Account Restrictions for SaaS objects", but I didnt see anything related to that. Is that possible through site initializer?

Thanks Amos. Ran `yarn format` in modules. I wasn't sure where to run it since we're in the new workspace and spinner build had some odd changes that we were running ant format-source in portal-impl instead to format the frontend files.

Also, re-pushed up the commit to enable Account Restriction, it was set on my to-do and I was going to manually update it for the ticket instead. Committed it altogether is just easier now. :)  I'll update the documentation too.

**Comment by amosfong** [comment]
nice, I didnt know account restriction was available in site initalizer.

**Comment by amosfong** [comment]
ci:forward

**Comment by amosfong** [comment]
ci:forward

**Pull request closed without merging**
