### PR TITLE
LRSD-4680 [PRM] URLParams search correction

### PR DESCRIPTION
**Pull request by eliasantosf**
Task: [LRSD-4680](https://liferay.atlassian.net/browse/LRSD-4680)

### CODE REVIEW

**Comment by eliasantosf** [comment]
ci:test:sf

**Review by eduardo-diniz — APPROVED** [review]
Downloaded the pull, tested and approved it :heavy_check_mark:  :rocket:

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by ryanschuhler** [comment]
thanks! https://github.com/brianchandotcom/liferay-portal/pull/151148

**Review by claricebrasil — APPROVED** [review]

**Pull request closed without merging**
