### PR TITLE
LRSD-4789 [CP 2.0] Add permissions to the Site Content Reviewer role in site initializer

### PR DESCRIPTION
**Pull request by pedroliveirav**
[LRSD-4789](https://liferay.atlassian.net/browse/LRSD-4789)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Review by kylembischof — APPROVED** [review]
looks good!

**Comment by kylembischof** [comment]
ci:forward

**Review by ryanschuhler — APPROVED** [review]

**Comment by kylembischof** [comment]
ci:forward:force

**Comment by kylembischof** [comment]
ci:forward:force

**Comment by kylembischof** [comment]
ci:forward:force

**Pull request closed without merging**
