### PR TITLE
LRSD-4403 [CP 2.0] Fix team members table when user is a critical incident contact

### PR DESCRIPTION
**Pull request by pedroliveirav**
[LRSD-4403](https://liferay.atlassian.net/browse/LRSD-4403)

### CODE REVIEW

**Review by amosfong — APPROVED** [review]

**Review by ryanschuhler — APPROVED** [review]
Looks good to me

**Comment by pedroliveirav** [comment]
ci:stop

**Comment by kylembischof** [comment]
ci:forward:force

**Comment by pedroliveirav** [comment]
ci:forward:force

**Comment by amosfong** [comment]
ci:forward:force

**Pull request closed without merging**
