### PR TITLE
LRSD-4165 [CP 2.0] Move Liferay PaaS out of Product Activation

### PR DESCRIPTION
**Pull request by pedroliveirav**
[LRSD-4165](https://liferay.atlassian.net/browse/LRSD-4165)

### CODE REVIEW

**Comment by pedroliveirav** [comment]
ci:test:sf

**Review by ryanschuhler — APPROVED** [review]

**Review by kylembischof — APPROVED** [review]

**Comment by pedroliveirav** [comment]
ci:forward

**Comment by jpince** [comment]
Same `Gradle build daemon` errors as other PRs. Please manually forward.

**Comment by pedroliveirav** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/151404

**Pull request closed without merging**
