### PR TITLE
LRSD-6623 [CP] Create Related Ticket IDs Field

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by ryanschuhler** [comment]
ci:forward

**Comment by JoMaAlves** [comment]
ci:forward

**Comment by ryanschuhler** [comment]
ci:forward

**Comment by ryanschuhler** [comment]
ci:forward

**Comment by ryanschuhler** [comment]
ci:forward:force

**Pull request closed without merging**
