### PR TITLE
[PRM] LRSD-747 Fix label for activity status

### PR DESCRIPTION
**Pull request by abfranca**

### CODE REVIEW

**Comment by abfranca** [comment]
ci:test:sf

**Comment by ryanschuhler** [comment]
ci:forward:force

**Comment by ryanschuhler** [comment]
ci:forward:force

**Comment by ryanschuhler** [comment]
@abfranca I am getting merge conflicts when I rebase to brians master, can you either rebase to brians latest or we wait for it to get merged into upstream and resolve the conflicts then?

**Comment by abfranca** [comment]
@ryanschuhler i'll rebase.

**Comment by ryanschuhler** [comment]
thanks! https://github.com/brianchandotcom/liferay-portal/pull/150491

**Pull request closed without merging**
