### PR TITLE
[CP] LRSD-6487 Replacing Okta SessionId with OAuth2 Token

### PR DESCRIPTION
**Pull request by jennyhchen**
https://liferay.atlassian.net/browse/LRSD-6487

@ryanschuhler 
I pulled latest to resolve the merge conflicts and tried to keep some of the other formatting to a minimum since I know you were going to do more sorting and other updates.

Also, I ended up changing the `const oauthToken = await getOrRequestToken()` codes to the useEffect() format you mentioned that Gemini updated and it looks like it helped to resolve some of the other frontend errors.

I'm going to guess that grabbing a token separately is considered the "side effect of functions" you mentioned before. It not only helped to reduce un-necessary calls with the null check in useProvisioningLicenseKeys, but it also helped in other JS/JSX files where it would update the token properly before handing off the value via the modals. Otherwise some calls were sending incorrect tokens with the value of "async () -> ba..." in the API requests. If you have more insight on why this would be happening or if there's a better solution, please educate me if possible and I can make any necessary changes. :) 

I've also tested most of the pages, but there are some tests I want to confirm that they work on UAT (as locally, I don't have Talend to migrate my local development accounts over to my CP account).

Related:
- https://github.com/liferay-customer-solutions/liferay-portal-ee/pull/81
- https://github.com/kylembischof/lfris-provisioning/pull/14

### CODE REVIEW

**Comment by ryanschuhler** [comment]
@jennyhchen all of the changes look good to me. I am however getting merge conflicts, can you rebase and repush it up?

**Comment by jennyhchen** [comment]
I pulled latest from liferay/liferay-portal master to make sure the conflicts wouldn't error out when sent to BChan. liferay-customer-solutions master was behind. Let me try and see if I can re-base off of both branches and where the conflict is coming from.

**Comment by jennyhchen** [comment]
Re-pushed changes. I made sure I was able to rebase on both liferay-customer-solutions/liferay-portal master and liferay/liferay-portal master branches.

**Review by ryanschuhler — APPROVED** [review]

**Comment by amosfong** [comment]
ci:forward

**Comment by amosfong** [comment]
Instead of passing the token around everywhere, can't we just get it when we add it to the provisioning request?

**Comment by jennyhchen** [comment]
As of right now? No we can't, I had tried to do that originally but I would have to, in addition, rewrite all the typescript/queries. I was going to make another ticket for after Ryan's typescript refactor. I would prefer all of the request went through useApollo (then the queries can just add 'raysource-rest' in the context) but CP isn't consistent enough yet. If all the queries were re-written to go through the apollo client, we would only need to put the token in one place.

**Pull request closed without merging**
