### PR TITLE
LRSD-1626 [CP 2.0] Clarify for customers what were the selected keys / what will be the generated keys

### PR DESCRIPTION
**Pull request by samuelleolopes**
[LRSD-1626](https://liferay.atlassian.net/browse/LRSD-1626)

### CODE REVIEW

**Comment by amosfong** [comment]
Looks good :)

**Comment by amosfong** [comment]
ci:forward

**Comment by amosfong** [comment]
@samuelleolopes, can you look at the SF error? You should be able to see it by running `yarn format` in the /modules folder

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:forward

**Comment by amosfong** [comment]
ci:forward

**Pull request closed without merging**
