### PR TITLE
[CP] LRSD-5487 Update to match Prod/UAT

### PR DESCRIPTION
**Pull request by jennyhchen**
https://liferay.atlassian.net/browse/LRSD-5487

Looks like the name was too long so Portal generated the account restriction differently on Prod/UAT so I updated site initializer files to match.

### CODE REVIEW

**Comment by amosfong** [comment]
Hey Jenny,

I'm not sure I understand. It looks like you made the names even longer, is that right?

**Comment by jennyhchen** [comment]
It was suppose to be I think r_accountEntryToLiferayExperienceCloudEnvironment_accountEntryId but for some reason when you/Kyle set the account restriction relationship manually on UAT/Prod, by default, r_liferayExperienceCloudEnvironment_accountEntryId is the one that got generated which I can't change and it causes the API to throw an error unless I match it with the generated field name UAT/Prod created.

**Comment by amosfong** [comment]
oh I see, ok that makes sense

**Comment by amosfong** [comment]
ci:forward

**Pull request closed without merging**
