### PR TITLE
LRSD-6567 Fix quickstart

### PR DESCRIPTION
**Pull request by ryanschuhler**

### CODE REVIEW

**Comment by ryanschuhler** [comment]
@jennyhchen would you mind testing this and see if it works any better for you? Im not fully convinced of the solution, but want to check if it works for you

**Comment by jennyhchen** [comment]
sure, in the middle of a refactor for the okta session replacement but I can test this after the major changes if it can wait

from the looks of the script changes, it does look like it would run better, thanks Ryan!

**Comment by amosfong** [comment]
@ryanschuhler What do you think about disabling the less used services like cron, mail, springboot. I think generally they are not needed unless you are specifically working on them. Unless they easily transparently work all the time, it might be good to disable them so we don't need to get everything working to make Remote App changes. (I just had to delete them locally myself so I could quickly get Liferay up to test something)

**Comment by ryanschuhler** [comment]
@amosfong , ya i was thinking about that. We could create a separate docker compose for them that you could spin up separately. Either that or we could make the run.sh call only the db and liferay, and the rest you would have to call by manually running docker compose up. Thoughts on a preference?

**Comment by amosfong** [comment]
> Either that or we could make the run.sh call only the db and liferay, and the rest you would have to call by manually running docker compose up

This sounds good, thanks!

**Comment by ryanschuhler** [comment]
@jennyhchen , whenever you get around to testing, I am hitting permission issues with mounting folders for deployment. Not sure why its happening now and wasnt before, but let me know if you hit those issues or not

**Comment by ryanschuhler** [comment]
ci:forward

**Comment by ryanschuhler** [comment]
ci:forward

**Pull request closed without merging**
