### PR TITLE
LRSD-6100 [CP] Sync callback info with Slack

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by ryanschuhler** [comment]
ci:forward

**Comment by ryanschuhler** [comment]
ci:forward

**Comment by ryanschuhler** [comment]
ci:forward:force

**Pull request closed without merging**
