### PR TITLE
LRSD-4980 Add customer-solutions team to test.properties

### PR DESCRIPTION
**Pull request by ryanschuhler**

### CODE REVIEW

**Comment by ryanschuhler** [comment]
ci:forward:force

**Comment by ryanschuhler** [comment]
we need to wait for [this](https://github.com/brianchandotcom/liferay-portal/pull/151868) to merge and retest this pull

**Comment by jpince** [comment]
@ryanschuhler if you are going with "Partner Portal" for the component name, this line in Clarice's PR will need to be adjusted to match: https://github.com/liferay-customer-solutions/liferay-portal/pull/200/files#diff-3d414bca30448574a25f98006cb08a5bd3276f62b36b65d45b19355177ac821fR5

**Comment by ryanschuhler** [comment]
ci:test

**Comment by jpince** [comment]
@ryanschuhler https://github.com/liferay-customer-solutions/liferay-portal/blob/8b907d4372975ffb97b653d146d8ec45be70f544/test.properties#L11666 :disappointed: 
Maybe check with AC team and see if they're still using it?

**Comment by ryanschuhler** [comment]
> @ryanschuhler
> 
> https://github.com/liferay-customer-solutions/liferay-portal/blob/8b907d4372975ffb97b653d146d8ec45be70f544/test.properties#L11666
> 
> 😞
> Maybe check with AC team and see if they're still using it?

oh good call, ill ask

**Comment by ryanschuhler** [comment]
ci:forward:force

**Pull request closed without merging**
