### PR TITLE
LRSD-2830 - JS error downloading ES license key as partner

### PR DESCRIPTION
**Pull request by velosofelipe64**
https://liferay.atlassian.net/browse/LRSD-2830

### CODE REVIEW

**Comment by velosofelipe64** [comment]
ci:test:sf

**Comment by kylembischof** [comment]
should partner managers have these permissions as well?

**Comment by velosofelipe64** [comment]
> should partner managers have these permissions as well?

Yeah, should all partner roles have this permissions?

**Review by ryanschuhler — APPROVED** [review]

**Comment by kylembischof** [comment]
> Yeah, should all partner roles have these permissions?

Just Partner Manager as well is fine for now. We are getting rid of the other 3 Partner roles sometime early next year most likely, since we no longer need them with the deprecation of PRM.

**Review by kylembischof — APPROVED** [review]

**Comment by ryanschuhler** [comment]
ci:test

**Comment by ryanschuhler** [comment]
ci:forward

**Pull request closed without merging**
