### PR TITLE
LRSD-4191 [PRM] Implementing sorting for listings

### PR DESCRIPTION
**Pull request by eliasantosf**
Tasks: [LRSD-4191](https://liferay.atlassian.net/browse/LRSD-4191),  [LRSD-4203](https://liferay.atlassian.net/browse/LRSD-4203),  [LRSD-4250](https://liferay.atlassian.net/browse/LRSD-4250),  [LRSD-4232](https://liferay.atlassian.net/browse/LRSD-4232)

### CODE REVIEW

**Comment by ryanschuhler** [comment]
ci:test:sf

**Review by ryanschuhler — APPROVED** [review]
Looks good @eliasantosf. It is a fair amount of code, so we will need to make sure we test thoroughly. Are there any areas you were unsure about you want to go over? or should I send it to Brian?

**Comment by eliasantosf** [comment]
There's just one small change that I'm testing at the moment, @ryanschuhler . As soon as you send it, I'll ask you again to review the changes.

**Comment by eliasantosf** [comment]
I've sent in the changes @ryanschuhler . I asked you for a review.

**Review by ryanschuhler — APPROVED** [review]
looks good!

**Comment by ryanschuhler** [comment]
ci:forward:force

**Pull request closed without merging**
