### PR TITLE
LRSD-2768 [CP 2.0] Renewal action by selecting the complimentary option

### PR DESCRIPTION
**Pull request by samuelleolopes**
[LRSD-2768](https://liferay.atlassian.net/browse/LRSD-2768)

### CODE REVIEW

**Comment by samuelleolopes** [comment]
ci:test:sf

**Review by ryanschuhler — APPROVED** [review]

**Comment by kylembischof** [comment]
@samuelleolopes does this need to be rebased off latest upstream? I noticed `sf` failed, and its referencing old site initializer directory.

**Comment by samuelleolopes** [comment]
ci:test:sf

**Comment by samuelleolopes** [comment]
ci:forward:force

**Comment by samuelleolopes** [comment]
> @samuelleolopes does this need to be rebased off latest upstream? I noticed `sf` failed, and its referencing old site initializer directory.

Thanks! @kylembischof , I rebased with master again.

**Comment by samuelleolopes** [comment]
ci:forward:force

**Comment by samuelleolopes** [comment]
ci:test:relevant

**Comment by amosfong** [comment]
ci:forward

**Pull request closed without merging**
