### PR TITLE
LRSD-4913 [PRM] Give Channels permission to complete MDF Request and Claim

### PR DESCRIPTION
**Pull request by claricebrasil**

### CODE REVIEW

**Comment by claricebrasil** [comment]
ci:test:sf

**Review by ryanschuhler — APPROVED** [review]

**Comment by ryanschuhler** [comment]
ci:forward:force

**Comment by ryanschuhler** [comment]
ci:reevaluate:1337401_6283

**Comment by ryanschuhler** [comment]
ci:forward:force

**Pull request closed without merging**
