### PR TITLE
[CP] LRSD-4178 409 Conflict when inviting team members or setting CIC(s)

### PR DESCRIPTION
**Pull request by jennyhchen**
https://liferay.atlassian.net/browse/LRSD-4178

- test cases: https://docs.google.com/spreadsheets/d/1MEm11EayZPksc6SGQwQLmDU-S7BYzIhruXMkNgqCNos/edit?pli=1&gid=0#gid=0
- subscriptions (mail) function calls Ryan mentioned previously isn't part of the ticket, will investigate and address it on a separate ticket if needed because it's being used in not just the one place
- not able to fully test PaaS until https://liferay.atlassian.net/browse/LRSD-4908 has been pushed to UAT
- will need to pull latest master as there may be a merge conflict with master-temp branch

### CODE REVIEW

**Comment by amosfong** [comment]
@jennyhchen is this ready for review?

**Comment by jennyhchen** [comment]
yep, let me know if I should change the "add" method to "assign" as well... leaving it up to you and Kyle

(I was only rebasing because Kyle was seeing some mismatch with liferay-customer-solutions and master).

**Comment by amosfong** [comment]
Nice, I think everything looks good :)

**Comment by amosfong** [comment]
ci:forward:force

**Pull request closed without merging**
