### PR TITLE
ISSD-3933, ISSD-3176 [PRM] Store the converted MDF Request and MDF Claim amount

### PR DESCRIPTION
**Pull request by abfranca**

### CODE REVIEW

**Comment by abfranca** [comment]
ci:test:sf

**Review by thaynam — APPROVED** [review]

**Comment by thaynam** [comment]
ci:forward:force

**Comment by thaynam** [comment]
ci:forward:force

**Comment by ryanschuhler** [comment]
ci:forward:force

**Comment by ryanschuhler** [comment]
ci:test:relevant

**Comment by ryanschuhler** [comment]
thanks! https://github.com/brianchandotcom/liferay-portal/pull/150362

**Pull request closed without merging**
