### PR TITLE
Lrsd 03260

### PR DESCRIPTION
**Pull request by amosfong**

### CODE REVIEW

**Comment by amosfong** [comment]
@ryanschuhler can you review, thanks!

**Comment by amosfong** [comment]
From https://github.com/liferay-customer-solutions/liferay-portal/pull/147

**Review by ryanschuhler — APPROVED** [review]
From what I can tell it looks good. It is a lot of code so hard to be sure without actually testing it, but if there are any specific areas you were uncertain about just let me know

**Comment by amosfong** [comment]
ci:forward:force

**Pull request closed without merging**
