### PR TITLE
LRSD-5784 [PRM] Update all pages in quickstart site initializer

### PR DESCRIPTION
**Pull request by claricebrasil**

### CODE REVIEW

**Comment by claricebrasil** [comment]
ci:test:sf

**Comment by claricebrasil** [comment]
ci:test:sf

**Comment by claricebrasil** [comment]
ci:test:sf

**Comment by claricebrasil** [comment]
ci:test:sf

**Comment by claricebrasil** [comment]
ci:test:sf

**Comment by claricebrasil** [comment]
ci:test:sf

**Comment by claricebrasil** [comment]
ci:test:sf

**Comment by ryanschuhler** [comment]
ci:forward

**Review by ryanschuhler — APPROVED** [review]

**Pull request closed without merging**
