### PR TITLE
LRSD-4911, LRSD-4769, LRSD-4867 [PRM] Tests Setup, MDF Request and Filter tests

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
ci:test:sf

**Comment by jpince** [comment]
```     [exec] $ node-scripts format --check
     [exec] 🛫 Running preflight...
     [exec] 📜 Validating tsconfig files...
     [exec] ℹ️ A total of 12 CPUs were detected: launching tsc in groups of 12 projects
     [exec] ℹ️ Going to check 0 modified projects
     [exec] 📝 Running format...
     [exec] ℹ️ Only running against files changed between 'master' and 'master-temp-1719015401787' branches. Use flag '--all' to run against all files.
     [exec] 📝 Formatting 11 files
     [exec] Error: Format checked 11 files
     [exec] 3 files have problems
     [exec] 
     [exec]     at format (file:///opt/dev/projects/github/liferay-portal/modules/_node-scripts/format/format.mjs:304:9)
     [exec]     at async main (file:///opt/dev/projects/github/liferay-portal/modules/_node-scripts/format/index.mjs:22:2)
```
@JoMaAlves see error from the log above

**Comment by claricebrasil** [comment]
@jpince since Joma and Eduardo are on vacation, i'll get the PR, fix the test errors and send it back, ok? So I'll close this PR and send it again.

**Comment by claricebrasil** [comment]
resent: https://github.com/liferay-customer-solutions/liferay-portal/pull/200

**Pull request closed without merging**
