### PR TITLE
[CP] LRSD-7202 - Translations for Security Vulnerability Page

### PR DESCRIPTION
**Pull request by abfranca**
https://liferay.atlassian.net/browse/LRSD-7202

### CODE REVIEW

**Comment by abfranca** [comment]
ci:test:sf

**Comment by abfranca** [comment]
ci:test:sf

**Comment by abfranca** [comment]
ci:test:sf

**Comment by abfranca** [comment]
ci:test:sf

**Comment by ryanschuhler** [comment]
https://github.com/liferay-customer-solutions/liferay-portal/pull/398

**Pull request closed without merging**
