### PR TITLE
LRSD-7576 Update code to new Category (multi-select) field

### PR DESCRIPTION
**Pull request by ryanschuhler**

### CODE REVIEW

**Comment by ryanschuhler** [comment]
ci:test

**Comment by ryanschuhler** [comment]
fyi @kylembischof @amosfong i added the frontend commits on top of @jennyhchen 's backend changes. Let us know if you want any changes, if not we can forward this and I think once it gets in we will be ready for security vulnerabilities to go to uat

**Comment by kylembischof** [comment]
Category is singular on the mockup, similarly to the jira field. Did Tiffany say somewhere she wanted it displayed as `Categories` plural? I understand that it is returning multiple values, but if its singular on jira and the frontend, seems a bit inconsistent and confusing if we name it plural inbetween those two end points.

**Comment by ryanschuhler** [comment]
Also to your point of it being singular in jira, i would expect they should change the name in jira to plural if they changed the functionality to multiple select, to avoid confusion

**Comment by ryanschuhler** [comment]
closing for https://github.com/liferay-customer-solutions/liferay-portal/pull/414

**Pull request closed without merging**
