### PR TITLE
[PRM] LRSD-713 Auto Save MDF as Draft when the session times out for the partner

### PR DESCRIPTION
**Pull request by abfranca**

### CODE REVIEW

**Comment by abfranca** [comment]
ci:test:sf

**Comment by ryanschuhler** [comment]
@abfranca I keep going back to this one to figure out a better way. Id prefer to just have to call the autoSave method once at the mdf request form level and once at the mdf request claim level, but that may require more restructuring then its worth. At the very least though we need to fix how every time it autosaves it runs all the validation rules and errors out all the empty required fields. This is a bad UX, and we should be able to save silently if we are autosaving.

I also noticed that if you refresh the page, it autosaved your last draft, but creates a new one, which could also be problematic, probably we would need to do some sort of redirect on creation so instead of using the /mdf/new url we redirect that url to mdf/id in order to avoid multiple draft creation.

All in all this feature is a little complex, but maybe we can meet and brainstorm some alternatives or fixes.

**Comment by abfranca** [comment]
@ryanschuhler yeah, i agree with all that you said. Maybe a brainstorm session could help us to find a better solution for this, we can meet whenever you have some time.

**Comment by ryanschuhler** [comment]
After our discussion I am closing this to clarify some requirements and refactor if we decide to move forward

**Pull request closed without merging**
