### PR TITLE
[CP] LRSD-6694 - Add link to past security advisories page + pagination

### PR DESCRIPTION
**Pull request by abfranca**
https://liferay.atlassian.net/browse/LRSD-6694

### CODE REVIEW

**Comment by abfranca** [comment]
ci:test:sf

**Comment by abfranca** [comment]
ci:test:sf

**Comment by abfranca** [comment]
ci:test:sf

**Comment by ryanschuhler** [comment]
thanks https://github.com/liferay-customer-solutions/liferay-portal/pull/408

**Pull request closed without merging**
