### PR TITLE
LRSD-5414 [CP] Create test for navigating to home page to ensure accounts list is loading correctly

### PR DESCRIPTION
**Pull request by abfranca**

### CODE REVIEW

**Comment by abfranca** [comment]
ci:test:sf

**Comment by amosfong** [comment]
that was quick :).

It makes sense to add to this test since it's the homepage. But can you make it look for a generic project because depending on how many projects there are, TESTACCOUNT01 may not be in the initial list. Maybe it needs just look for the html container instead of the content.

**Comment by abfranca** [comment]
@amosfong yeah, makes sense. I've sent the changes :)

**Comment by amosfong** [comment]
looks good to me

**Comment by amosfong** [comment]
ci:forward

**Pull request closed without merging**
