### PR TITLE
ISSD-2602 ISSD-2588 [CP 2.0] add phone number and customer email field to escalation form

### PR DESCRIPTION
**Pull request by kylembischof**

### CODE REVIEW

**Comment by kylembischof** [comment]
ci:test:sf

**Review by amosfong — APPROVED** [review]

**Comment by kylembischof** [comment]
ci:foward

**Comment by kylembischof** [comment]
ci:forward

**Comment by kylembischof** [comment]
ci:reevaluate:1367401_5551

**Comment by kylembischof** [comment]
ci:forward:force

**Comment by kylembischof** [comment]
ci:forward:force

**Pull request closed without merging**
