### PR TITLE
[PRM] LRSD-4783 Fix the behavior on close date filter

### PR DESCRIPTION
**Pull request by eduardo-diniz**

### CODE REVIEW

**Review by ryanschuhler — APPROVED** [review]

**Comment by ryanschuhler** [comment]
ci:forward:force

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by eduardo-diniz** [comment]
ci:test:sf:force

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by jpince** [comment]
@eduardo-diniz I think this needs the commits from https://github.com/brianchandotcom/liferay-portal/pull/151537. You should be able to retest if they're in upstream, or just cherry-pick them on top of your branch.

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by eduardo-diniz** [comment]
ci:test:sf

**Comment by ryanschuhler** [comment]
ci:forward:force

**Pull request closed without merging**
