### PR TITLE
[CP] LRSD-5536 Update site initializer to add permissions for User, Account Member, Account Administrator, Organization User, Partner Manager

### PR DESCRIPTION
**Pull request by jennyhchen**
https://liferay.atlassian.net/browse/LRSD-5536

### CODE REVIEW

**Comment by kylembischof** [comment]
ci:test:sf

**Review by kylembischof — APPROVED** [review]

**Review by amosfong — APPROVED** [review]
These are manual steps on https://liferay.atlassian.net/wiki/spaces/IS/pages/2108228311/Server+Refresh+-+Manual+Steps right? can you cross out those steps now? thanks

**Comment by amosfong** [comment]
ci:forward

**Comment by jennyhchen** [comment]
Yep! Updated the doc =)  Was waiting for the merge but can do it now. Thanks!

**Pull request closed without merging**
