### PR TITLE
LRSD-5420 Update run.sh

### PR DESCRIPTION
**Pull request by ryanschuhler**

### CODE REVIEW

**Comment by jennyhchen** [comment]
https://liferay.atlassian.net/browse/LRSD-5761  fyi, ticket created for patching

**Comment by amosfong** [comment]
this seems good, are you waiting for anything to forward?

**Comment by ryanschuhler** [comment]
im not confident bchan will merge this yet, gonna try a few more things today first, then decide what to send him, people can use it in the mean time if needed though, seems to work for me consistently to get the basics up

**Comment by ryanschuhler** [comment]
closing for https://github.com/liferay-customer-solutions/liferay-portal/pull/294

**Pull request closed without merging**
