### PR TITLE
LRSD-5047 Reduce complimentary keys duration to 30 days

### PR DESCRIPTION
**Pull request by amosfong**

### CODE REVIEW

**Comment by amosfong** [comment]
@ryanschuhler can you review soon? need this for release, thanks!

**Review by ryanschuhler — APPROVED** [review]
Looks good!

**Comment by ryanschuhler** [comment]
@amosfong changes look good, only issue will be if we merge the moving of the site initializer before this or not

**Comment by amosfong** [comment]
I think we'll have to replay commits onto the CX once it's ready for release

**Pull request closed without merging**
